### ISSUE TITLE
Error compiling BassFX "Unknown type name 'BOOL'"

### ISSUE THREAD

**Issue by jalone87** [Treata11/CBass#3]
Hi,
in a pretty fresh Xcode project for iOS in Swift, having embedded the Bass and BassFX frameworks:
- `import Bass` seems to work smoothly 
- but when trying `import BassFX` (and the same could happen for other modules), in a Swift file, then compilation of related bass_fx.h C header fails with various `Unknown type name 'BOOL'`.

- Xcode 15.3 
- C compiler GNU-17

Is this a potential issue of the SPM Package, or of the bass library (of which i have no experience to judge) or is a problem with my project configuration.

Thank you

**Comment by Treata11** [comment]
Hi @jalone87,
Thanks for the heads up. I think the issue should be fixed right now. 

In header `bass.h` there's a type alias:
```c
#ifdef __OBJC__
typedef int BOOL32;
#define BOOL BOOL32 // override objc's BOOL
#endif
```
And as you might know, all the other headers of Un4seen rely on `bass.h`. 
The code above already existed in some headers of various modules, like `BassMIDI` & `BassMix` etc...
But it didn't in most other modules like `BassFX` that you mentioned. 

So, what was the issue? Why to **re-declare** a definition twice, both in `bass.h` & the module's specific header?
Well, I don't have a good answer for that because I don't know if this I'm going to explain is a bug or a feature :) 

In Bridged headers, it seems like that the **Preprocessor directives** like #ifdef and #define are processed at a very early stage of compilation. They essentially manipulate the source code before it's passed to the compiler. However, their scope is limited to the specific header file where they're defined.
So, directives like the alias mentioned above has to be re-declared in the scope of each bridged header ... 

I'll let Un4seen devs know about this issue & thank you again

**Comment by jalone87** [comment]
I was wondering the same, thanks @Treata11  for the clarification and for being so quick

I just tested, all compiles now, great work
